### ISSUE TITLE
cl0p scraper broken

### ISSUE THREAD

**Issue by captainGeech42** [captainGeech42/ransomwatch#63]
**Describe the bug**
Cl0p scraper out of date

**Logs**
```
Traceback (most recent call last):
  File "/app/ransomwatch.py", line 66, in main
    s.scrape_victims()
  File "/app/sites/cl0p.py", line 21, in scrape_victims
    victim_list = soup.find("div", class_="collapse-section").find_all("li")
AttributeError: 'NoneType' object has no attribute 'find_all'
```

should probably just update this to the v3 site as well

**Comment by OkkarMin** [comment]
It seems like Cl0p added
- queue system and
- captcha
